### ISSUE TITLE
“「秦至汉初(前246 至前104)历法研究」原文於漢高祖7年5月記為己巳朔，恐有誤”

### ISSUE THREAD

**Issue by zizicici** [kanasimi/CeJS#10]
我查阅了李忠林先生 2016 年出版的专著《秦至汉初立法研究》，根据 P 217，其 7 年 5 月对应的公历为“前 200 年 6 月 2 日” ，朔干支是“己卯”。

应该是修正了。

**Comment by kanasimi** [comment]
thank you.
fixed
