### ISSUE TITLE
Wikimedia file url direct derivate of filename ?

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/CeJS#14]
Hello, I'm doing a light review of our former downloading system before replacing it, and I discovered that [Wikimedia file url is direct derivate of filename](https://github.com/lingua-libre/CommonsDownloadTool/blob/master/commons_download_tool.py#L59-L89) ? 👀 

I'm not sure how, but it could be interesting to know.

(PS: to keep you informed about wikiapi on Lili what chanel should I use ? Discord ? github projects ?)

**Comment by kanasimi** [comment]
Yes, it is interesting to get the url directly. But we cannot know about the file attributes then. And the method does not including derivatives. That would be a bit of a hassle for some people. However I will document it, thank you!

I do not have regular task on lingualibre, so you may contact me on github now.

**Comment by hugolpz** [comment]
Lines 68 and 77 i think there is support for what you call derivative.

There is always need for bot help on Lingualibre. But first I assume that you are both busy in other IRL (family), professional, open source projects so I won't call you over to help around. If someday you have personal motivations for hanging out on LinguaLibre, tell me. We will then need someone to welcome you, show you possible challenges to pick up, possibly write down requirements. (I could be your guide depending on the period.)

**Comment by kanasimi** [comment]
The "derivatives" means "Only download files with these formats" at [here](https://kanasimi.github.io/wikiapi/Wikiapi.html#download).

I'm honored to help LinguaLibre. The tasks I can do are listed [here](https://lingualibre.org/wiki/LinguaLibre:Bot#Welcome_to_Kanashimi_.26_Cewbot_.21) for your reference. The codes are prepared [here](https://github.com/kanasimi/wikibot/tree/master/routine) so it will not take long time.

**Comment by hugolpz** [comment]
Note for later, script of specific interest for LinguaLibre :
- [welcome_bot.js](https://github.com/kanasimi/wikibot/blob/master/routine/20210419.welcome_bot.js)
- [Auto-archiver.js](https://github.com/kanasimi/wikibot/blob/master/routine/20210429.Auto-archiver.js)

See also https://github.com/hugolpz/WikiapiJS-Eggs/issues/4 .
