### ISSUE TITLE
Translation issue with message Wikimedia:Cejs-temple-name/fr

### ISSUE THREAD

**Issue by verdy-p** [kanasimi/CeJS#16]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=cejs-temple-name&group=cejs&language=fr

I suppose this is not the name of a temple monument, but this refers to a name of a person or deity, as it is celebrated in temples for religious purpose (e.g. the name to respectfully reference Buddha, rather than the historical real name of the person when they were living; this could also apply to Mahomet, Jesus-Christ, saints and prophets, or honoric names for rules, even if they are not celebrated in "temples" but in comparable places like churches, synagogues, mosquees, mausoleums, palaces, and other celebration places or in meetings or in legal acts).

Am I right ? If so, this would not translate the same in all languages (the basic form "Temple name" alone is then semantically ambiguous and needs to be described because on first reading one could think it only refers to a monument/building and not to a person or deity).

May be this could be changed in English to "Celebration name" or "Honorific name".

----
Note also that some person have other legal names (e.g. Chinese people have a legal name for use in China, written in Chinese characters, and can oficially register an additional name written in Latin for use on international passports, or international commercial transactions, bank records...) Many countries maintain these alternate legal names in their official national registries of identities (one good examples being artist names, spouse names, parental names before adult age, adoption names, names for use by migrants for residence in other countries than their origin nationality, names given after legal change of nationality or for granted dual nationality...)

**Comment by kanasimi** [comment]
Well, it means https://en.wikipedia.org/wiki/Temple_name

I think "Nom de temple"  can be used as its translation.

This is actually a unique attribute of Chinese monarchs, so it may be difficult for people in other countries to understand.

**Comment by verdy-p** [comment]
I prefer "Nom au temple" (litterally "Name at the temple", i.e. used in celebrations) which gives less confusion.
It could as well be "Nom de célébration" (litterally "Name of/for celebration" or "Celebrational name")

But you confim that this is like the celebrated names of rules... or deities, sacred people and saints like the "Buddha" (which was not really named like this during his life) or the "Christ" or "Jesus Christ" (which was of course not living with that attribute added for celbrating him after his death, in fact after his resurrection), or "Saint XXX" for all saint men and women (used like this on their yearly day of celebration, while the scriptures and historic books only refer to their first name, possibly qualified by names of their fathers, or place of residence, or other attributes), or "Bienheureux/Bienheureuse XXX" (Blessed XXX) which are also celebration names after their death but without being necessarily "sacred" like saints.

Other celeration names include "Little Father of the People" (Staline...)

So the general concept is effectively "Celebration name" (not necessarily religious, and not necessarily attached to a specific type of place for celebrations, and not necessarily given after their death for some political rulers, or for reincarnated spiritual guides like the Dalai Lama for Buddhism, or similar names given in Hindouistic religions to some elected children that get a sacred status long before they become active spiritual guides) !

**Comment by kanasimi** [comment]
The deceased emperor is worshipped in the ancestral shrine. Therefore, the temple here refers to this ancestral shrine.
