### ISSUE TITLE
Translation issue with message "Wikimedia:Cejs-work status-finished/en"

### ISSUE THREAD

**Issue by verdy-p** [kanasimi/CeJS#17]
Typo in English source message: replace "Compeleted" by "Completed".

URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=cejs-work_status-finished&group=cejs&language=en

**Comment by kanasimi** [comment]
Thank you. I just fixed the error. Please let me know if there are any more questions, thank you.
