### ISSUE TITLE
Translation issue with message Wikimedia:Cejs-the-chunk-do-not-has-regular-.content length/fr

### ISSUE THREAD

**Issue by verdy-p** [kanasimi/CeJS#21]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=cejs-the-chunk-do-not-has-regular-.content_length&group=cejs&language=fr

Very pour English, bad grammar. Replace:
> The chunk **do not has** a regular .content_length!

by:
> The chunk **does not have** a regural .content_length!

and preferably indicate this refers to an attribute name (the dot alone is not clear enough):
> The chunk **does not have** a regural value for its 'content_length'!

and preferably as well indicate what kind of value was expected, such as
> The chunk **does not have** a regural integer value for its 'content_length'!

**Comment by kanasimi** [comment]
Thank you. I edited it [here](https://translatewiki.net/wiki/Wikimedia:Cejs-the-chunk-do-not-has-regular-.content_length/en) first in case the changes were missed.

**Comment by verdy-p** [comment]
editing the /en version does not make it visible for other translators.
The existing /fr version was correct according to your change in /en, now you need to update the base translation by importing it nad this will close this issue. Thanks.
