### ISSUE TITLE
Trailing spaces in i18n messages

### ISSUE THREAD

**Issue by Nikerabbit** [kanasimi/CeJS#32]
You have multiple messages with trailing whitespace. This causes issues for translatewiki.net synchronization, because MediaWiki does not support trailing spaces in page contents. Can you remove those spaces, please?

**Comment by verdy-p** [comment]
The alternative, if those spaces are needed, is to include them as HTML entities, i.e. `&#32;` (and document it in the /qqq doc subpage); such use is rare in messages, essentially for a few messages related to isolated word separators or substrings needed for inline formatting of lists (note also that the space is not used as a word separator in several East or Souther-eastern Asian scripts, and in some historic scripts, where it may only be acceptable in combination with some explicit punctuation signs).

**Comment by Nikerabbit** [comment]
Thank you!
