### ISSUE TITLE
Standalone version of the mediawiki parser

### ISSUE THREAD

**Issue by simontaurus** [kanasimi/CeJS#37]
Hi,

I'm using CeJS to parse wikipages and manipulate the contained templates (see https://github.com/OpenSemanticLab/mediawiki-extensions-MwJson/blob/main/modules/ext.MwJson.parser/MwJson_parser.js#L135).
It works well so far - many thanks for your work!

The only problem is that CeJS is quite a huge & complex framework - and for my purpose I only a fraction of it's features.
For improved performance I've tried to isolate the parser into a single (minified) file, but failed due to the overall complexity.
Do you think there's a way to get a standalone version of the mediawiki parser?

**Comment by kanasimi** [comment]
<s>I think perhaps I can make a version that includes only the necessary files. It would still be an npm. I wonder if that would be appropriate for your situation?</s>
Sorry. I found a problem with the integration. So I would like to know the size of CeJS that you can accept, which is now about 12M after unpacking?

**Comment by simontaurus** [comment]
Thanks for your affort so far. The target application requires client-side js (browser).
Currently, there's a sequencial loading of the CeJS modules with a total size of 735.4 kB which tooks about 3840 ms on this [Testpage](https://sinergie.open-semantic-lab.org/wiki/TestPage). So any reduction would help.
Ideas so far:

1. Minify the files
2. Replace sequencial loading by parallel loading around here https://github.com/kanasimi/CeJS/blob/master/ce.js#L4126 
3. Replace dynamic loading by static references (may also allow to run browserify on the npm)
4. Deliver all files packed in one file
5. Remove unused code (of course, a lot of work if done manually)

My hope is that a combination of 1 + 3 + 4 is doable, so we get a minified file "cejs_parser.js" containing all files listet below.


ce.js?_=1663034017556 | kanasimi.github.io | script | load.php?modules=ext.InteractiveSemanticGraph | 107 kB | 211 ms
-- | -- | -- | -- | -- | --
wiki.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 6.3 kB | 127 ms
compatibility.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 28.0 kB | 140 ms
native.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 48.7 kB | 135 ms
date.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 40.2 kB | 148 ms
code.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 6.9 kB | 119 ms
namespace.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 36.2 kB | 122 ms
net.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 21.4 kB | 142 ms
Windows.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 8.4 kB | 115 ms
DOM.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 94.7 kB | 133 ms
data.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 18.2 kB | 129 ms
locale.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 27.0 kB | 148 ms
numeral.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 13.7 kB | 119 ms
gettext_plural_rules.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 1.1 kB | 123 ms
de-DE.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 3.2 kB | 132 ms
parser.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 17.9 kB | 127 ms
task.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 35.5 kB | 145 ms
Ajax.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 36.0 kB | 129 ms
MIME.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 1.6 kB | 129 ms
query.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 11.9 kB | 123 ms
page.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 41.5 kB | 130 ms
storage.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 5.3 kB | 125 ms
Flow.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 4.5 kB | 125 ms
Page.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 2.4 kB | 127 ms
list.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 24.2 kB | 129 ms
edit.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 17.2 kB | 129 ms
wikitext.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 37.2 kB | 134 ms
section.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 18.1 kB | 114 ms
misc.js | kanasimi.github.io | xhr | ce.js?_=1663034017556:4180 | 21.1 kB | 131 ms
  |   |   |   |   |  
Total |   |   |   | 735.4 kB | 3840 ms

**Comment by kanasimi** [comment]
I think maybe I can combine these files in a single file, with ce.js, for a total of about 1.5 m. But this would require writing another tool. Is this acceptable to you?

**Comment by simontaurus** [comment]
Do you mean "another tool" => changes in my application tool? Of course, that's fine for me

**Comment by kanasimi** [comment]
Well, I need time to write the tool and test the feasibility, so I may have to ask you to wait for some time.

**Comment by simontaurus** [comment]
That's completely fine. I'm glad if there's a solution at all =)

**Comment by kanasimi** [comment]
Ok. I am working on this...

**Comment by kanasimi** [comment]
Please try to see [this](https://github.com/kanasimi/CeJS_wiki)

**Comment by simontaurus** [comment]
Many thanks!
It works as expected - I only faced some minor issues (see https://github.com/RepoLab/CeJS_wiki/tree/minor-workarounds-and-fixes)

- auto init (important when CeJS_wiki.js is loaded before the script using it): https://github.com/RepoLab/CeJS_wiki/commit/e3f8ab5c984990c94ed42f20033b169215021821
- at least on older Chrome Browser additional dependancies failed to load (I asume they contain polyfills): https://github.com/RepoLab/CeJS_wiki/commit/b7b9c14487c7357fff00d46190f45934b634104c, as a workaround I've added the polyfill for Array.at() directly to CeJS_wiki.js (https://github.com/RepoLab/CeJS_wiki/commit/7d16ba77878fa4769d911459663f27221fa96957)
- if running on an actual mediawiki server, CeJS_wiki.js tries to init wiki_API but fails because wiki_API.language_code_to_site_alias is undefined. As a workaround I skip the initialization: https://github.com/RepoLab/CeJS_wiki/commit/ebc5356c49ff102d64aeeb2c3537331fa39645ee (I asume wiki_API is optional for the pure parser functionality)

As a result we have about 2350 KB for the unminified and about 650 KB for the minified version of CeJS_wiki.js and loading time goes down from about 3800 ms to about 100 ms (even lower when bundled by MW Resource Loader) - That's great! :D

**Comment by kanasimi** [comment]
Since I will be constantly updating the code, I think a better way to do this is to push it directly into CeJS. I will release a new version later that tries to solve the first two issues. The last issue seems to be a judgment problem. The `wiki_API.mw_web_session` is a session that operates in a web environment. For example, the Wikipedia widget. So I must know first what `mediawiki server` you are referring to...

**Comment by kanasimi** [comment]
I've got a new version out. Maybe you can try this version?
