### ISSUE TITLE
Remove references from build folder for strings to translate

### ISSUE THREAD

**Issue by Abijeet** [kanasimi/CeJS#38]
I am a translation liason on translatewiki.net where CeJS is a project available for translation.

We've been noticing that there are references to strings added from files under the `_build` folder. 

![image](https://user-images.githubusercontent.com/1685517/191721910-ad12828e-6096-4160-bcb9-fd1727641c97.png)

Other examples: [[1](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=cejs-españa&group=cejs)]. [[2](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=cejs-french-republican-calendar&group=cejs)], [[3](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=cejs-function-name-unmatched&group=cejs)]

Can we remove the references of these messages (and others like them) in the build folders?

CC: @translatewiki

**Comment by kanasimi** [comment]
From my point of view, adding a reference would allow the translator to understand the application context of the sentence and therefore translate it more accurately.
If you mean only the files under _build, I recently made the mistake of adding the files under CeJS_wiki and will remove them in the next few days.
Could you tell me about your considerations?

**Comment by Abijeet** [comment]
> If you mean only the files under _build, I recently made the mistake of adding the files under CeJS_wiki and will remove them in the next few days.

Yes, I meant just the references to the files under the `_build` folder.

**Comment by kanasimi** [comment]
Okay. Please wait for this update to see the situation. Thank you.
