### ISSUE TITLE
ReferenceError: constant_function is not defined

### ISSUE THREAD

**Issue by strefethen** [kanasimi/CeJS#41]
@kanasimi 

I've just stumbled into this exception when my app is starting and I see this package has been recently updated. This package is pulled into my app a as a dependency of wikiapi. Are you familiar with this? It's now a blocking issue for me. I'm going to try and pin this package at the prior version and see if I can get around it.

<img width="753" alt="image" src="https://github.com/kanasimi/CeJS/assets/118724/a7eabd5a-1db3-4de7-a3bb-e0fbe9d70b51">

Exception has occurred: ReferenceError: constant_function is not defined
  at Function._.constant_function (eval at <anonymous> (.../node_modules/cejs/_for include/node.loader.js:86:2), <anonymous>:2080:18)
    at eval (eval at <anonymous> (.../node_modules/cejs/_for include/node.loader.js:86:2), <anonymous>:2090:5)
    at eval (eval at <anonymous> (.../node_modules/cejs/_for include/node.loader.js:86:2), <anonymous>:3219:2)

The version from the package.json is 4.5.5.

I'm struggling to follow this code as constant_function is 

```javascript
	constant_function = function(value) {
		value = String(value);

		if (!(value in constant_function)
			// true/false/Number/null/undefined/global variables only!
			// && ((value in globalThis) || !isNaN(value))
			) {
			constant_function[value] = new Function('return(' + value + ')');
		}
		return constant_function[value];
	};
```

**Comment by strefethen** [comment]
I've discovered this occurs when trying to use skipFiles in launch.json in VSCode. I've removed this and the error is no longer getting raised. Here's the skipFiles I was using. IMO, this should work and I think points to some sort of coding error.

```json
            "skipFiles": [
                // Slow startup issue https://github.com/microsoft/vscode-js-debug/issues/1179
                "${workspaceRoot}/node_modules/**/*.js",
                "<node_internals>/**"
            ]
```

**Comment by kanasimi** [comment]
You are right, there are some bugs in the code. I will improve it and test the code and release a new version as soon as possible. Then you can use the code in the same way as before and see if there are any problems.
