### ISSUE TITLE
Numerous exceptions are thrown on startup making debugging non-CeJS projects difficult

### ISSUE THREAD

**Issue by strefethen** [kanasimi/CeJS#42]
Hi @kanasimi, I wanted to try to offer some constructive feedback on this package so please don't take the following in a negative tone rather as feedback for possible improvements.

My project uses wikiapi works great but the CeJS dependency makes debugging my own project pretty frustrating because this package throws so many exceptions on startup as it appears to be written relying on try...catch vs. proper error/null checking.

I've reviewed some of the CeJS code and I would highly recommend spending some time researching best practices for using try...catch as there are several anti-patterns present in this codebase. Instead of using try catch and swallowing exceptions I would highly recommend changing patterns to use standard error checking logic.

Like the prior issue I logged I would like to be able to use the VSCode's debugger with both Caught and Uncaught exceptions checked to debug _my own code_ but CeJS throws so many exceptions on startup it makes these options unusable.

<img width="1156" alt="image" src="https://github.com/kanasimi/CeJS/assets/118724/d6c77e4d-305c-4762-9ed3-2300eb994039">

For example, code like the following is simply not a best practice, using empty try catch blocks vs. using standard error checking logic. Also, writing code that could fail in a catch block can also lead to additional problems. For example, what if KEY_not_native is not defined correctly? That could have unexpected/intended consequences and as a result be difficult to debug.

```javascript
  ...
				try {
					delete test_Funciton.size;
				} catch (e) {
				}
        ...
		} catch (e) {
			// Don't have standard Object.defineProperty()!
			Object.defineProperty[KEY_not_native] = true;
		}
```

Again, hopefully you read this as it was intended.

**Comment by strefethen** [comment]
One more note, it looks like there are lot of assumptions in the CeJS package that the code is running in the browser so lots of exceptions get thrown when running in NodeJS. For example:

```javascript
function new_XMLHttpRequest() {
   return new XMLHttpRequest();
}
```

Also, this code raises concerns as it appears to be hijacking this and many other browser functions.

**Comment by kanasimi** [comment]
Thank you for your participation in the development of this library. There are of course major flaws in this library. I know it's not easy to improve it all at once. Maybe we could start with a simple part, refactor a part of the code and push it once, so that we can improve the library step by step?

**Comment by strefethen** [comment]
Hi @kanasimi, my primary usage is through wikiapi which (as I believe you know) I've used for a long time and his worked well (thank you for that!). I haven't studied CeJS enough to understand what it's doing/for and despite reviewing the readme (I can't read Chinese) I'm not sure I understand the intent. I wish I have more time to help with code commits but my hacking with these packages is a hobby for which I have little time.

If I can offer any advice it would be what I mentioned above, take some time learning about effective use of try catch and also when/how to throw exceptions. That would certainly be a good start to help cleaning up the code.

**Comment by kanasimi** [comment]
Thank you for your advice. I will improve the code. I think at least you will not stop because of cijs when debugging code, this can solve the major trouble, is it right?

Can you tell me your VSCode settings? I also use VSCode debug, but it doesn't stop here. Maybe we have different settings?

**Comment by strefethen** [comment]
If you look in the Breakpoints window there are two options at the top regarding exceptions which can be helpful when you aren't sure where a problem is. I usually have these unchecked but when I can't figure out where the exception is occurring these can be very useful. If you enable Caught Exceptions you'll see that CeJS will likely be throwing a few dozen errors on startup.

<img width="313" alt="image" src="https://github.com/kanasimi/CeJS/assets/118724/e84e4a98-a52c-4a1f-9ed5-bb79b41f48e0">

**Comment by kanasimi** [comment]
Most of the codes are for [feature detection](https://en.wikipedia.org/wiki/Feature_detection_(web_development)). I'll try to see if there are other ways to bypass the detection.

**Comment by strefethen** [comment]
Or perhaps detect if the environment is NodeJS and not a browse then skip whatever checks are browser specific.
