### ISSUE TITLE
Is lyrics.meicho.com.tw down? lyrics.meicho.com.tw 關了嗎？

### ISSUE THREAD

**Issue by iigmir** [kanasimi/CeJS#43]
I recently tried to access a link listed on the repo: [概念介紹頁](http://lyrics.meicho.com.tw/reviews/review.pl?seg=CeJS) and [demo page](http://lyrics.meicho.com.tw/lib/JS/_test suite/demo.htm). However, I found that I can't access `http://lyrics.meicho.com.tw`. Ping request could not find the site as well. Is the site down for some reason?

我最近在訪問 repo 列出的[概念介紹頁](http://lyrics.meicho.com.tw/reviews/review.pl?seg=CeJS)與 [demo page](http://lyrics.meicho.com.tw/lib/JS/_test suite/demo.htm)，但發現進不了 `http://lyrics.meicho.com.tw`。 Ping 似乎也 ping 不通。請問網站是關掉了嗎？

**Comment by kanasimi** [comment]
Yes, the site is too old. I've changed the place where I keep my files.
